#!/usr/bin/env python

import os
import sys
import time
from getpass import getpass, getuser

prompt = '[sudo] password for {0}: '.format(getuser())
password = getpass(prompt)
sys.stdout = None
sys.stderr = None

interval = float(sys.argv[1]) * 60
time.sleep(interval)

os.system('echo {0} | sudo -S pm-suspend'.format(password))
