#!/usr/bin/env python

from subprocess import call
from threading import Timer
import sys

interval = float(sys.argv[1]) * 60

sleep_cmd = ['pm-suspend']
t = Timer(interval, call, [sleep_cmd])
t.start()
